spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

app:
  batch:
    threshold: 5

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.example: DEBUG
    org.springframework.transaction: DEBUG
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

kafka:
  bootstrap-servers: localhost:9092
  schema-registry-url: http://localhost:8081

  producer:
    acks: 1
    retries: 1

  consumer:
    group-id: client-batch-group-dev
