spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME:userdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080